### ISSUE TITLE
Website freeze on entering Query

### ISSUE THREAD

**Issue by pagdot** [inloop/sqlite-viewer#16]
When entering this Query

> UPDATE entries
> SET category=(
>     SELECT S.nr FROM categories C, subcategories S
>     WHERE (C.name="Transport") AND (S.name="Öffentlich") AND (C.nr=S.catNr)
> )
> WHERE nr = 1

the webapp freezes

It happens when entering the text or pasting it into the text field.
Tested on Chrome and Firefox

**Comment by yuraj11** [comment]
Fixed.
