### ISSUE TITLE
How to open the specified sql file?

### ISSUE THREAD

**Issue by hgy987654** [inloop/sqlite-viewer#20]
I am a novice.
I want to open the specified sql file.
When the web page is opened, the specified sql file is directly opened without dragging or opening.
Where can I modify the source code?
Thank you

**Comment by TomTasche** [comment]
You can pass a URL to a database to load immediately via an URL parameter: https://github.com/inloop/sqlite-viewer/blob/gh-pages/js/main.js#L109-L123

**Comment by yuraj11** [comment]
> You can also load remote files (using JS ajax, remote server must send Access-Control-Allow-Origin:*): http://inloop.github.io/sqlite-viewer/?url=http://example.com/data.sqlite
