### ISSUE TITLE
Exporting results to mysql OR xlsx

### ISSUE THREAD

**Issue by yalattas** [inloop/sqlite-viewer#25]
Dears,
I have an SQLite file that I couldn't open anywhere including Visual Studio Code with SQLite extension but your solution did.
I want to export the result into MySQL OR xlsx but I couldn't find it. I highly suggest you enable the export feature at least to CSV for us to get the benefit out of it. Currently, I am seeing my data without any use of the benefit.

Appreciate it if you could help me with that

**Comment by yuraj11** [comment]
Added option for CSV export in  #35.
