### ISSUE TITLE
Load DB via URL Parameter

### ISSUE THREAD

**Issue by gavinr** [inloop/sqlite-viewer#4]
Hi, thanks for this project- it's really cool!

Would it be possible to allow the loading of a sqlite db via url parameter? Like `http://inloop.github.io/sqlite-viewer?url=http://mysite.com/data.sqlite`?

**Comment by yuraj11** [comment]
Thanks and good idea! :+1:  
It's implemented now, use in this format:
http://inloop.github.io/sqlite-viewer/?url=<http address here>
Keep in mind that remote server must have set http header - Access-Control-Allow-Origin: \* otherwise It will not work.

**Comment by gavinr** [comment]
Thanks! Here it is in action: https://github.com/gavinr/university-city-mo-crime

ddfe01e5cae5d30a358b704c2142701033063826
